# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20180321_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pic',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
    ]
