# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_course_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='pdf'),
            preserve_default=False,
        ),
    ]
